import { db, clientsTable, deliveryAddresses, eq, and, ClientAddress } from "@workspace/db";

// Internal interface used for seeding logic (includes isDeliveryDefault)
interface Address {
  id: string;
  city: string;
  name: string;
  type: "Billing Address" | "Delivery Address" | "Other";
  state: string;
  country: string;
  pincode: string;
  address1: string;
  address2: string;
  contactNo: string;
  isBillingDefault: boolean;
  isDeliveryDefault: boolean;
}

export async function seedClients(): Promise<void> {
  const clientData = [
    // CL001 - Zara
    {
      clientCode: "CL001",
      brandName: "Zara",
      contactName: "John Doe",
      email: "john@zara.com",
      altEmail: "",
      contactNo: "+91 9876543210",
      altContactNo: "",
      country: "India",
      countryOfOrigin: "Spain",
      hasGst: true,
      gstNo: "GSTIN001",
      address1: "Zara Store, MG Road",
      address2: "Near City Center",
      state: "Maharashtra",
      city: "Mumbai",
      pincode: "400001",
      addresses: [
        {
          id: "addr1",
          city: "Mumbai",
          name: "Zara Billing",
          type: "Billing Address",
          state: "Maharashtra",
          country: "India",
          pincode: "400001",
          address1: "Zara Store, MG Road",
          address2: "Near City Center",
          contactNo: "+91 9876543210",
          isBillingDefault: true,
          isDeliveryDefault: false,
        },
        {
          id: "addr2",
          city: "Mumbai",
          name: "Zara Delivery",
          type: "Delivery Address",
          state: "Maharashtra",
          country: "India",
          pincode: "400002",
          address1: "Warehouse 1, MIDC",
          address2: "Andheri East",
          contactNo: "+91 9876543211",
          isBillingDefault: false,
          isDeliveryDefault: true,
        },
      ] as Address[],
      invoiceCurrency: "INR",
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system",
      customClientCode: "ZARA001",
    },
    // CL002 - H&M
    {
      clientCode: "CL002",
      brandName: "H&M",
      contactName: "Jane Smith",
      email: "jane@hm.com",
      altEmail: "",
      contactNo: "+91 9876543211",
      altContactNo: "",
      country: "India",
      countryOfOrigin: "Sweden",
      hasGst: true,
      gstNo: "GSTIN002",
      address1: "H&M, Phoenix Mall",
      address2: "Lower Parel",
      state: "Maharashtra",
      city: "Mumbai",
      pincode: "400013",
      addresses: [
        {
          id: "addr3",
          city: "Mumbai",
          name: "H&M Billing",
          type: "Billing Address",
          state: "Maharashtra",
          country: "India",
          pincode: "400013",
          address1: "H&M, Phoenix Mall",
          address2: "Lower Parel",
          contactNo: "+91 9876543211",
          isBillingDefault: true,
          isDeliveryDefault: false,
        },
        {
          id: "addr4",
          city: "Mumbai",
          name: "H&M Delivery",
          type: "Delivery Address",
          state: "Maharashtra",
          country: "India",
          pincode: "400093",
          address1: "Warehouse 2, Bhiwandi",
          address2: "Thane",
          contactNo: "+91 9876543212",
          isBillingDefault: false,
          isDeliveryDefault: true,
        },
      ] as Address[],
      invoiceCurrency: "INR",
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system",
      customClientCode: "HM001",
    },
    // CL003 - Uniqlo
    {
      clientCode: "CL003",
      brandName: "Uniqlo",
      contactName: "Taro Yamada",
      email: "taro@uniqlo.com",
      altEmail: "",
      contactNo: "+91 9876543212",
      altContactNo: "",
      country: "India",
      countryOfOrigin: "Japan",
      hasGst: true,
      gstNo: "GSTIN003",
      address1: "Uniqlo, Select Citywalk",
      address2: "Saket",
      state: "Delhi",
      city: "New Delhi",
      pincode: "110017",
      addresses: [
        {
          id: "addr5",
          city: "New Delhi",
          name: "Uniqlo Billing",
          type: "Billing Address",
          state: "Delhi",
          country: "India",
          pincode: "110017",
          address1: "Uniqlo, Select Citywalk",
          address2: "Saket",
          contactNo: "+91 9876543212",
          isBillingDefault: true,
          isDeliveryDefault: false,
        },
        {
          id: "addr6",
          city: "New Delhi",
          name: "Uniqlo Delivery",
          type: "Delivery Address",
          state: "Delhi",
          country: "India",
          pincode: "110001",
          address1: "Warehouse 3, Okhla",
          address2: "Phase II",
          contactNo: "+91 9876543213",
          isBillingDefault: false,
          isDeliveryDefault: true,
        },
      ] as Address[],
      invoiceCurrency: "INR",
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system",
      customClientCode: "UNIQLO001",
    },
    // CL004 - Adidas
    {
      clientCode: "CL004",
      brandName: "Adidas",
      contactName: "Hans Mueller",
      email: "hans@adidas.com",
      altEmail: "",
      contactNo: "+91 9876543213",
      altContactNo: "",
      country: "India",
      countryOfOrigin: "Germany",
      hasGst: true,
      gstNo: "GSTIN004",
      address1: "Adidas, Forum Mall",
      address2: "Koramangala",
      state: "Karnataka",
      city: "Bangalore",
      pincode: "560095",
      addresses: [
        {
          id: "addr7",
          city: "Bangalore",
          name: "Adidas Billing",
          type: "Billing Address",
          state: "Karnataka",
          country: "India",
          pincode: "560095",
          address1: "Adidas, Forum Mall",
          address2: "Koramangala",
          contactNo: "+91 9876543213",
          isBillingDefault: true,
          isDeliveryDefault: false,
        },
        {
          id: "addr8",
          city: "Bangalore",
          name: "Adidas Delivery",
          type: "Delivery Address",
          state: "Karnataka",
          country: "India",
          pincode: "560058",
          address1: "Warehouse 4, Peenya",
          address2: "Industrial Area",
          contactNo: "+91 9876543214",
          isBillingDefault: false,
          isDeliveryDefault: true,
        },
      ] as Address[],
      invoiceCurrency: "INR",
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system",
      customClientCode: "ADIDAS001",
    },
    // CL005 - Nike
    {
      clientCode: "CL005",
      brandName: "Nike",
      contactName: "Sarah Johnson",
      email: "sarah@nike.com",
      altEmail: "",
      contactNo: "+91 9876543214",
      altContactNo: "",
      country: "India",
      countryOfOrigin: "USA",
      hasGst: true,
      gstNo: "GSTIN005",
      address1: "Nike, DLF Mall",
      address2: "Sector 18",
      state: "Haryana",
      city: "Gurugram",
      pincode: "122001",
      addresses: [
        {
          id: "addr9",
          city: "Gurugram",
          name: "Nike Billing",
          type: "Billing Address",
          state: "Haryana",
          country: "India",
          pincode: "122001",
          address1: "Nike, DLF Mall",
          address2: "Sector 18",
          contactNo: "+91 9876543214",
          isBillingDefault: true,
          isDeliveryDefault: false,
        },
        {
          id: "addr10",
          city: "Gurugram",
          name: "Nike Delivery",
          type: "Delivery Address",
          state: "Haryana",
          country: "India",
          pincode: "122002",
          address1: "Warehouse 5, Udyog Vihar",
          address2: "Phase IV",
          contactNo: "+91 9876543215",
          isBillingDefault: false,
          isDeliveryDefault: true,
        },
      ] as Address[],
      invoiceCurrency: "INR",
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system",
      customClientCode: "NIKE001",
    },
    // CL006 - Levi's
    {
      clientCode: "CL006",
      brandName: "Levi's",
      contactName: "Rajesh Kumar",
      email: "rajesh@levis.com",
      altEmail: "",
      contactNo: "+91 9876543215",
      altContactNo: "",
      country: "India",
      countryOfOrigin: "USA",
      hasGst: true,
      gstNo: "GSTIN006",
      address1: "Levi's, South Ex",
      address2: "New Delhi",
      state: "Delhi",
      city: "New Delhi",
      pincode: "110049",
      addresses: [
        {
          id: "addr11",
          city: "New Delhi",
          name: "Levi's Billing",
          type: "Billing Address",
          state: "Delhi",
          country: "India",
          pincode: "110049",
          address1: "Levi's, South Ex",
          address2: "New Delhi",
          contactNo: "+91 9876543215",
          isBillingDefault: true,
          isDeliveryDefault: false,
        },
        {
          id: "addr12",
          city: "New Delhi",
          name: "Levi's Delivery",
          type: "Delivery Address",
          state: "Delhi",
          country: "India",
          pincode: "110002",
          address1: "Warehouse 6, Naraina",
          address2: "Industrial Area",
          contactNo: "+91 9876543216",
          isBillingDefault: false,
          isDeliveryDefault: true,
        },
      ] as Address[],
      invoiceCurrency: "INR",
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system",
      customClientCode: "LEVIS001",
    },
    // CL007 - Puma
    {
      clientCode: "CL007",
      brandName: "Puma",
      contactName: "Anita Mehta",
      email: "anita@puma.com",
      altEmail: "",
      contactNo: "+91 9876543216",
      altContactNo: "",
      country: "India",
      countryOfOrigin: "Germany",
      hasGst: true,
      gstNo: "GSTIN007",
      address1: "Puma, Orion Mall",
      address2: "Rajajinagar",
      state: "Karnataka",
      city: "Bangalore",
      pincode: "560010",
      addresses: [
        {
          id: "addr13",
          city: "Bangalore",
          name: "Puma Billing",
          type: "Billing Address",
          state: "Karnataka",
          country: "India",
          pincode: "560010",
          address1: "Puma, Orion Mall",
          address2: "Rajajinagar",
          contactNo: "+91 9876543216",
          isBillingDefault: true,
          isDeliveryDefault: false,
        },
        {
          id: "addr14",
          city: "Bangalore",
          name: "Puma Delivery",
          type: "Delivery Address",
          state: "Karnataka",
          country: "India",
          pincode: "560058",
          address1: "Warehouse 7, Peenya",
          address2: "Industrial Area",
          contactNo: "+91 9876543217",
          isBillingDefault: false,
          isDeliveryDefault: true,
        },
      ] as Address[],
      invoiceCurrency: "INR",
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system",
      customClientCode: "PUMA001",
    },
    // CL008 - Reebok
    {
      clientCode: "CL008",
      brandName: "Reebok",
      contactName: "David Smith",
      email: "david@reebok.com",
      altEmail: "",
      contactNo: "+91 9876543217",
      altContactNo: "",
      country: "India",
      countryOfOrigin: "USA",
      hasGst: true,
      gstNo: "GSTIN008",
      address1: "Reebok, City Centre",
      address2: "Salt Lake",
      state: "West Bengal",
      city: "Kolkata",
      pincode: "700064",
      addresses: [
        {
          id: "addr15",
          city: "Kolkata",
          name: "Reebok Billing",
          type: "Billing Address",
          state: "West Bengal",
          country: "India",
          pincode: "700064",
          address1: "Reebok, City Centre",
          address2: "Salt Lake",
          contactNo: "+91 9876543217",
          isBillingDefault: true,
          isDeliveryDefault: false,
        },
        {
          id: "addr16",
          city: "Kolkata",
          name: "Reebok Delivery",
          type: "Delivery Address",
          state: "West Bengal",
          country: "India",
          pincode: "700001",
          address1: "Warehouse 8, Howrah",
          address2: "Industrial Area",
          contactNo: "+91 9876543218",
          isBillingDefault: false,
          isDeliveryDefault: true,
        },
      ] as Address[],
      invoiceCurrency: "INR",
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system",
      customClientCode: "REEBOK001",
    },
    // CL009 - Under Armour
    {
      clientCode: "CL009",
      brandName: "Under Armour",
      contactName: "Priya Shah",
      email: "priya@underarmour.com",
      altEmail: "",
      contactNo: "+91 9876543218",
      altContactNo: "",
      country: "India",
      countryOfOrigin: "USA",
      hasGst: true,
      gstNo: "GSTIN009",
      address1: "Under Armour, Forum",
      address2: "Koramangala",
      state: "Karnataka",
      city: "Bangalore",
      pincode: "560095",
      addresses: [
        {
          id: "addr17",
          city: "Bangalore",
          name: "Under Armour Billing",
          type: "Billing Address",
          state: "Karnataka",
          country: "India",
          pincode: "560095",
          address1: "Under Armour, Forum",
          address2: "Koramangala",
          contactNo: "+91 9876543218",
          isBillingDefault: true,
          isDeliveryDefault: false,
        },
        {
          id: "addr18",
          city: "Bangalore",
          name: "Under Armour Delivery",
          type: "Delivery Address",
          state: "Karnataka",
          country: "India",
          pincode: "560058",
          address1: "Warehouse 9, Peenya",
          address2: "Industrial Area",
          contactNo: "+91 9876543219",
          isBillingDefault: false,
          isDeliveryDefault: true,
        },
      ] as Address[],
      invoiceCurrency: "INR",
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system",
      customClientCode: "UNDERARMOUR001",
    },
    // CL010 - Decathlon
    {
      clientCode: "CL010",
      brandName: "Decathlon",
      contactName: "Suresh Reddy",
      email: "suresh@decathlon.com",
      altEmail: "",
      contactNo: "+91 9876543219",
      altContactNo: "",
      country: "India",
      countryOfOrigin: "France",
      hasGst: true,
      gstNo: "GSTIN010",
      address1: "Decathlon, Inorbit",
      address2: "Malad",
      state: "Maharashtra",
      city: "Mumbai",
      pincode: "400064",
      addresses: [
        {
          id: "addr19",
          city: "Mumbai",
          name: "Decathlon Billing",
          type: "Billing Address",
          state: "Maharashtra",
          country: "India",
          pincode: "400064",
          address1: "Decathlon, Inorbit",
          address2: "Malad",
          contactNo: "+91 9876543219",
          isBillingDefault: true,
          isDeliveryDefault: false,
        },
        {
          id: "addr20",
          city: "Mumbai",
          name: "Decathlon Delivery",
          type: "Delivery Address",
          state: "Maharashtra",
          country: "India",
          pincode: "400093",
          address1: "Warehouse 10, Bhiwandi",
          address2: "Thane",
          contactNo: "+91 9876543220",
          isBillingDefault: false,
          isDeliveryDefault: true,
        },
      ] as Address[],
      invoiceCurrency: "INR",
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system",
      customClientCode: "DECATHLON001",
    },
    // CL011 - Lululemon
    {
      clientCode: "CL011",
      brandName: "Lululemon",
      contactName: "Maria Chen",
      email: "maria@lululemon.com",
      altEmail: "",
      contactNo: "+91 9876543220",
      altContactNo: "",
      country: "India",
      countryOfOrigin: "Canada",
      hasGst: true,
      gstNo: "GSTIN011",
      address1: "Lululemon, Ambience",
      address2: "Vasant Kunj",
      state: "Delhi",
      city: "New Delhi",
      pincode: "110070",
      addresses: [
        {
          id: "addr21",
          city: "New Delhi",
          name: "Lululemon Billing",
          type: "Billing Address",
          state: "Delhi",
          country: "India",
          pincode: "110070",
          address1: "Lululemon, Ambience",
          address2: "Vasant Kunj",
          contactNo: "+91 9876543220",
          isBillingDefault: true,
          isDeliveryDefault: false,
        },
        {
          id: "addr22",
          city: "New Delhi",
          name: "Lululemon Delivery",
          type: "Delivery Address",
          state: "Delhi",
          country: "India",
          pincode: "110002",
          address1: "Warehouse 11, Naraina",
          address2: "Industrial Area",
          contactNo: "+91 9876543221",
          isBillingDefault: false,
          isDeliveryDefault: true,
        },
      ] as Address[],
      invoiceCurrency: "INR",
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system",
      customClientCode: "LULULEMON001",
    },
    // CL012 - Fila
    {
      clientCode: "CL012",
      brandName: "Fila",
      contactName: "Amit Patel",
      email: "amit@fila.com",
      altEmail: "",
      contactNo: "+91 9876543221",
      altContactNo: "",
      country: "India",
      countryOfOrigin: "Italy",
      hasGst: true,
      gstNo: "GSTIN012",
      address1: "Fila, Phoenix",
      address2: "Whitefield",
      state: "Karnataka",
      city: "Bangalore",
      pincode: "560066",
      addresses: [
        {
          id: "addr23",
          city: "Bangalore",
          name: "Fila Billing",
          type: "Billing Address",
          state: "Karnataka",
          country: "India",
          pincode: "560066",
          address1: "Fila, Phoenix",
          address2: "Whitefield",
          contactNo: "+91 9876543221",
          isBillingDefault: true,
          isDeliveryDefault: false,
        },
        {
          id: "addr24",
          city: "Bangalore",
          name: "Fila Delivery",
          type: "Delivery Address",
          state: "Karnataka",
          country: "India",
          pincode: "560058",
          address1: "Warehouse 12, Peenya",
          address2: "Industrial Area",
          contactNo: "+91 9876543222",
          isBillingDefault: false,
          isDeliveryDefault: true,
        },
      ] as Address[],
      invoiceCurrency: "INR",
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system",
      customClientCode: "FILA001",
    },
    // CL013 - New Balance
    {
      clientCode: "CL013",
      brandName: "New Balance",
      contactName: "Sanjay Joshi",
      email: "sanjay@newbalance.com",
      altEmail: "",
      contactNo: "+91 9876543222",
      altContactNo: "",
      country: "India",
      countryOfOrigin: "USA",
      hasGst: true,
      gstNo: "GSTIN013",
      address1: "New Balance, Palladium",
      address2: "Lower Parel",
      state: "Maharashtra",
      city: "Mumbai",
      pincode: "400013",
      addresses: [
        {
          id: "addr25",
          city: "Mumbai",
          name: "New Balance Billing",
          type: "Billing Address",
          state: "Maharashtra",
          country: "India",
          pincode: "400013",
          address1: "New Balance, Palladium",
          address2: "Lower Parel",
          contactNo: "+91 9876543222",
          isBillingDefault: true,
          isDeliveryDefault: false,
        },
        {
          id: "addr26",
          city: "Mumbai",
          name: "New Balance Delivery",
          type: "Delivery Address",
          state: "Maharashtra",
          country: "India",
          pincode: "400093",
          address1: "Warehouse 13, Bhiwandi",
          address2: "Thane",
          contactNo: "+91 9876543223",
          isBillingDefault: false,
          isDeliveryDefault: true,
        },
      ] as Address[],
      invoiceCurrency: "INR",
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system",
      customClientCode: "NEWBALANCE001",
    },
    // CL014 - ASICS
    {
      clientCode: "CL014",
      brandName: "ASICS",
      contactName: "Naoki Tanaka",
      email: "naoki@asics.com",
      altEmail: "",
      contactNo: "+91 9876543223",
      altContactNo: "",
      country: "India",
      countryOfOrigin: "Japan",
      hasGst: true,
      gstNo: "GSTIN014",
      address1: "ASICS, Select Citywalk",
      address2: "Saket",
      state: "Delhi",
      city: "New Delhi",
      pincode: "110017",
      addresses: [
        {
          id: "addr27",
          city: "New Delhi",
          name: "ASICS Billing",
          type: "Billing Address",
          state: "Delhi",
          country: "India",
          pincode: "110017",
          address1: "ASICS, Select Citywalk",
          address2: "Saket",
          contactNo: "+91 9876543223",
          isBillingDefault: true,
          isDeliveryDefault: false,
        },
        {
          id: "addr28",
          city: "New Delhi",
          name: "ASICS Delivery",
          type: "Delivery Address",
          state: "Delhi",
          country: "India",
          pincode: "110001",
          address1: "Warehouse 14, Okhla",
          address2: "Phase II",
          contactNo: "+91 9876543224",
          isBillingDefault: false,
          isDeliveryDefault: true,
        },
      ] as Address[],
      invoiceCurrency: "INR",
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system",
      customClientCode: "ASICS001",
    },
    // CL015 - Skechers
    {
      clientCode: "CL015",
      brandName: "Skechers",
      contactName: "Kiran Reddy",
      email: "kiran@skechers.com",
      altEmail: "",
      contactNo: "+91 9876543224",
      altContactNo: "",
      country: "India",
      countryOfOrigin: "USA",
      hasGst: true,
      gstNo: "GSTIN015",
      address1: "Skechers, Forum",
      address2: "Koramangala",
      state: "Karnataka",
      city: "Bangalore",
      pincode: "560095",
      addresses: [
        {
          id: "addr29",
          city: "Bangalore",
          name: "Skechers Billing",
          type: "Billing Address",
          state: "Karnataka",
          country: "India",
          pincode: "560095",
          address1: "Skechers, Forum",
          address2: "Koramangala",
          contactNo: "+91 9876543224",
          isBillingDefault: true,
          isDeliveryDefault: false,
        },
        {
          id: "addr30",
          city: "Bangalore",
          name: "Skechers Delivery",
          type: "Delivery Address",
          state: "Karnataka",
          country: "India",
          pincode: "560058",
          address1: "Warehouse 15, Peenya",
          address2: "Industrial Area",
          contactNo: "+91 9876543225",
          isBillingDefault: false,
          isDeliveryDefault: true,
        },
      ] as Address[],
      invoiceCurrency: "INR",
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system",
      customClientCode: "SKECHERS001",
    },
    // CL016 - Vans
    {
      clientCode: "CL016",
      brandName: "Vans",
      contactName: "Emily Stone",
      email: "emily@vans.com",
      altEmail: "",
      contactNo: "+91 9876543225",
      altContactNo: "",
      country: "India",
      countryOfOrigin: "USA",
      hasGst: true,
      gstNo: "GSTIN016",
      address1: "Vans, Phoenix",
      address2: "Whitefield",
      state: "Karnataka",
      city: "Bangalore",
      pincode: "560066",
      addresses: [
        {
          id: "addr31",
          city: "Bangalore",
          name: "Vans Billing",
          type: "Billing Address",
          state: "Karnataka",
          country: "India",
          pincode: "560066",
          address1: "Vans, Phoenix",
          address2: "Whitefield",
          contactNo: "+91 9876543225",
          isBillingDefault: true,
          isDeliveryDefault: false,
        },
        {
          id: "addr32",
          city: "Bangalore",
          name: "Vans Delivery",
          type: "Delivery Address",
          state: "Karnataka",
          country: "India",
          pincode: "560058",
          address1: "Warehouse 16, Peenya",
          address2: "Industrial Area",
          contactNo: "+91 9876543226",
          isBillingDefault: false,
          isDeliveryDefault: true,
        },
      ] as Address[],
      invoiceCurrency: "INR",
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system",
      customClientCode: "VANS001",
    },
    // CL017 - Timberland
    {
      clientCode: "CL017",
      brandName: "Timberland",
      contactName: "Michael Brown",
      email: "michael@timberland.com",
      altEmail: "",
      contactNo: "+91 9876543226",
      altContactNo: "",
      country: "India",
      countryOfOrigin: "USA",
      hasGst: true,
      gstNo: "GSTIN017",
      address1: "Timberland, Ambience",
      address2: "Vasant Kunj",
      state: "Delhi",
      city: "New Delhi",
      pincode: "110070",
      addresses: [
        {
          id: "addr33",
          city: "New Delhi",
          name: "Timberland Billing",
          type: "Billing Address",
          state: "Delhi",
          country: "India",
          pincode: "110070",
          address1: "Timberland, Ambience",
          address2: "Vasant Kunj",
          contactNo: "+91 9876543226",
          isBillingDefault: true,
          isDeliveryDefault: false,
        },
        {
          id: "addr34",
          city: "New Delhi",
          name: "Timberland Delivery",
          type: "Delivery Address",
          state: "Delhi",
          country: "India",
          pincode: "110002",
          address1: "Warehouse 17, Naraina",
          address2: "Industrial Area",
          contactNo: "+91 9876543227",
          isBillingDefault: false,
          isDeliveryDefault: true,
        },
      ] as Address[],
      invoiceCurrency: "INR",
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system",
      customClientCode: "TIMBERLAND001",
    },
    // CL018 - Converse
    {
      clientCode: "CL018",
      brandName: "Converse",
      contactName: "Rajiv Gupta",
      email: "rajiv@converse.com",
      altEmail: "",
      contactNo: "+91 9876543227",
      altContactNo: "",
      country: "India",
      countryOfOrigin: "USA",
      hasGst: true,
      gstNo: "GSTIN018",
      address1: "Converse, Palladium",
      address2: "Lower Parel",
      state: "Maharashtra",
      city: "Mumbai",
      pincode: "400013",
      addresses: [
        {
          id: "addr35",
          city: "Mumbai",
          name: "Converse Billing",
          type: "Billing Address",
          state: "Maharashtra",
          country: "India",
          pincode: "400013",
          address1: "Converse, Palladium",
          address2: "Lower Parel",
          contactNo: "+91 9876543227",
          isBillingDefault: true,
          isDeliveryDefault: false,
        },
        {
          id: "addr36",
          city: "Mumbai",
          name: "Converse Delivery",
          type: "Delivery Address",
          state: "Maharashtra",
          country: "India",
          pincode: "400093",
          address1: "Warehouse 18, Bhiwandi",
          address2: "Thane",
          contactNo: "+91 9876543228",
          isBillingDefault: false,
          isDeliveryDefault: true,
        },
      ] as Address[],
      invoiceCurrency: "INR",
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system",
      customClientCode: "CONVERSE001",
    },
    // CL019 - The North Face
    {
      clientCode: "CL019",
      brandName: "The North Face",
      contactName: "Sofia Martinez",
      email: "sofia@thenorthface.com",
      altEmail: "",
      contactNo: "+91 9876543228",
      altContactNo: "",
      country: "India",
      countryOfOrigin: "USA",
      hasGst: true,
      gstNo: "GSTIN019",
      address1: "The North Face, DLF",
      address2: "Sector 18",
      state: "Haryana",
      city: "Gurugram",
      pincode: "122001",
      addresses: [
        {
          id: "addr37",
          city: "Gurugram",
          name: "The North Face Billing",
          type: "Billing Address",
          state: "Haryana",
          country: "India",
          pincode: "122001",
          address1: "The North Face, DLF",
          address2: "Sector 18",
          contactNo: "+91 9876543228",
          isBillingDefault: true,
          isDeliveryDefault: false,
        },
        {
          id: "addr38",
          city: "Gurugram",
          name: "The North Face Delivery",
          type: "Delivery Address",
          state: "Haryana",
          country: "India",
          pincode: "122002",
          address1: "Warehouse 19, Udyog Vihar",
          address2: "Phase IV",
          contactNo: "+91 9876543229",
          isBillingDefault: false,
          isDeliveryDefault: true,
        },
      ] as Address[],
      invoiceCurrency: "INR",
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system",
      customClientCode: "NORTHFACE001",
    },
    // CL020 - Urban Outfitters
    {
      clientCode: "CL020",
      brandName: "Urban Outfitters",
      contactName: "George Allen",
      email: "george@urbanoutfitters.com",
      altEmail: "",
      contactNo: "+91 9876543229",
      altContactNo: "+91",
      country: "India",
      countryOfOrigin: "India",
      hasGst: false,
      gstNo: null,
      address1: null,
      address2: null,
      state: null,
      city: null,
      pincode: null,
      addresses: [
        {
          id: "5x0y992e",
          city: "Mumbai",
          name: "Urban Outfit India",
          type: "Billing Address",
          state: "Maharashtra",
          country: "India",
          pincode: "400069",
          address1: "Unit 204, Urban Plaza",
          address2: "Fashion Park, Andheri East",
          contactNo: "+91 8989898989",
          isBillingDefault: true,
          isDeliveryDefault: false,
        },
        {
          id: "x474urp5",
          city: "Thane",
          name: "Rohan Mehta",
          type: "Delivery Address",
          state: "Maharashtra",
          country: "India",
          pincode: "421302",
          address1: "Warehouse No. 18, Metro Logistics Park",
          address2: "Bhiwandi Industrial Area",
          contactNo: "+91 9000012345",
          isBillingDefault: false,
          isDeliveryDefault: true,
        },
      ] as Address[],
      invoiceCurrency: "INR",
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "admin@taar.com",
      customClientCode: "URBANOUTFIT001",
    },
  ];

  // Insert clients inside a transaction
  await db.transaction(async (tx) => {
    let insertedClients = 0;
    let insertedAddresses = 0;

    for (const client of clientData) {
      const { addresses, ...clientFields } = client;

      // Map addresses to ClientAddress[] (remove isDeliveryDefault)
      const clientAddresses: ClientAddress[] = addresses.map((addr) => ({
        id: addr.id,
        type: addr.type,
        name: addr.name,
        contactNo: addr.contactNo,
        address1: addr.address1,
        address2: addr.address2,
        city: addr.city,
        state: addr.state,
        pincode: addr.pincode,
        country: addr.country,
        isBillingDefault: addr.isBillingDefault,
      }));

      const insertValues = {
        ...clientFields,
        altEmail: clientFields.altEmail ?? null,
        altContactNo: clientFields.altContactNo ?? null,
        country: clientFields.country ?? null,
        countryOfOrigin: clientFields.countryOfOrigin ?? null,
        hasGst: clientFields.hasGst ?? false,
        gstNo: clientFields.gstNo ?? null,
        address1: clientFields.address1 ?? null,
        address2: clientFields.address2 ?? null,
        state: clientFields.state ?? null,
        city: clientFields.city ?? null,
        pincode: clientFields.pincode ?? null,
        addresses: clientAddresses,
        invoiceCurrency: clientFields.invoiceCurrency ?? null,
        isActive: clientFields.isActive ?? true,
        isDeleted: clientFields.isDeleted ?? false,
        updatedBy: clientFields.updatedBy ?? clientFields.createdBy,
        customClientCode: clientFields.customClientCode ?? null,
      };

      const [inserted] = await tx
        .insert(clientsTable)
        .values(insertValues)
        .onConflictDoNothing()
        .returning({ id: clientsTable.id, clientCode: clientsTable.clientCode });

      if (inserted) {
        insertedClients++;
        const clientId = inserted.id;

        // Insert delivery addresses into the separate table
        if (addresses && addresses.length > 0) {
          for (const addr of addresses) {
            if (addr.isDeliveryDefault) {
              const existing = await tx
                .select({ id: deliveryAddresses.id })
                .from(deliveryAddresses)
                .where(
                  and(
                    eq(deliveryAddresses.clientId, clientId),
                    eq(deliveryAddresses.clientAddressId, addr.id),
                    eq(deliveryAddresses.isDeleted, false),
                  ),
                )
                .limit(1);

              const deliveryData = {
                clientId,
                clientAddressId: addr.id,
                label: addr.name || "Delivery Address",
                addressLine1: addr.address1,
                addressLine2: addr.address2,
                city: addr.city,
                state: addr.state,
                country: addr.country,
                pincode: addr.pincode,
                isDefault: addr.isDeliveryDefault,
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
                isDeleted: false,
                deletedBy: null,
                deletedAt: null,
              };

              if (existing.length > 0) {
                await tx
                  .update(deliveryAddresses)
                  .set({
                    label: deliveryData.label,
                    addressLine1: deliveryData.addressLine1,
                    addressLine2: deliveryData.addressLine2,
                    city: deliveryData.city,
                    state: deliveryData.state,
                    country: deliveryData.country,
                    pincode: deliveryData.pincode,
                    isDefault: deliveryData.isDefault,
                    updatedAt: new Date().toISOString(),
                  })
                  .where(eq(deliveryAddresses.id, existing[0].id));
              } else {
                await tx.insert(deliveryAddresses).values(deliveryData);
                insertedAddresses++;
              }
            }
          }
        }
      }
    }

    console.log(
      `[master-seed] Clients: ${insertedClients} inserted, ${insertedAddresses} delivery addresses inserted/updated`,
    );
  });
}