import { db, vendorsTable, BankAccount, PaymentAttachment, VendorAddress } from "@workspace/db";

export async function seedVendors(): Promise<void> {
  const vendorData = [
    // 1. Arvind Mills
    {
      vendorCode: "VEN001",
      brandName: "Arvind Mills",
      contactName: "Rahul Sharma",
      email: "rahul@arvind.com",
      altEmail: "rahul.alternate@arvind.com",
      contactNo: "+91 9876543220",
      altContactNo: "+91 9876543221",
      country: "India",
      hasGst: true,
      gstNo: "24ABCDE1234F1Z5",
      bankName: "ICICI Bank",
      accountNo: "123456789012",
      ifscCode: "ICIC0000123",
      bankAccounts: [
        {
          bankName: "ICICI Bank",
          ifscCode: "ICIC0000123",
          accountNo: "123456789012",
        },
        {
          bankName: "HDFC Bank",
          ifscCode: "HDFC0000123",
          accountNo: "987654321098",
        },
      ] as BankAccount[],
      address1: "Arvind Mills Complex",
      address2: "Naroda Road",
      pincode: "380025",
      state: "Gujarat",
      city: "Ahmedabad",
      addresses: [
        {
          id: "addr_arvind1",
          city: "Ahmedabad",
          name: "Arvind Mills Office",
          type: "Office",
          state: "Gujarat",
          country: "India",
          pincode: "380025",
          address1: "Arvind Mills Complex",
          address2: "Naroda Road",
          contactNo: "+91 9876543220",
          isBillingDefault: true,
        },
        {
          id: "addr_arvind2",
          city: "Mumbai",
          name: "Arvind Mumbai Warehouse",
          type: "Warehouse",
          state: "Maharashtra",
          country: "India",
          pincode: "400093",
          address1: "Warehouse 12, Bhiwandi",
          address2: "Thane",
          contactNo: "+91 9876543221",
          isBillingDefault: false,
        },
      ] as VendorAddress[],
      paymentAttachments: [] as PaymentAttachment[],
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system@erp.com",
    },
    // 2. Raymond
    {
      vendorCode: "VEN002",
      brandName: "Raymond",
      contactName: "Amit Patel",
      email: "amit@raymond.com",
      altEmail: "",
      contactNo: "+91 9876543222",
      altContactNo: "",
      country: "India",
      hasGst: true,
      gstNo: "27ABCDE5678F1Z5",
      bankName: "HDFC Bank",
      accountNo: "234567890123",
      ifscCode: "HDFC0000456",
      bankAccounts: [
        {
          bankName: "HDFC Bank",
          ifscCode: "HDFC0000456",
          accountNo: "234567890123",
        },
      ] as BankAccount[],
      address1: "Raymond House",
      address2: "Lal Bahadur Shastri Marg",
      pincode: "400001",
      state: "Maharashtra",
      city: "Mumbai",
      addresses: [
        {
          id: "addr_raymond1",
          city: "Mumbai",
          name: "Raymond Head Office",
          type: "Office",
          state: "Maharashtra",
          country: "India",
          pincode: "400001",
          address1: "Raymond House",
          address2: "Lal Bahadur Shastri Marg",
          contactNo: "+91 9876543222",
          isBillingDefault: true,
        },
        {
          id: "addr_raymond2",
          city: "Bangalore",
          name: "Raymond Bangalore Office",
          type: "Office",
          state: "Karnataka",
          country: "India",
          pincode: "560095",
          address1: "Raymond Showroom, Forum Mall",
          address2: "Koramangala",
          contactNo: "+91 9876543223",
          isBillingDefault: false,
        },
      ] as VendorAddress[],
      paymentAttachments: [] as PaymentAttachment[],
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system@erp.com",
    },
    // 3. Sutlej Textiles
    {
      vendorCode: "VEN003",
      brandName: "Sutlej Textiles",
      contactName: "Sunil Kumar",
      email: "sunil@sutlej.com",
      altEmail: "sunil.alt@sutlej.com",
      contactNo: "+91 9876543224",
      altContactNo: "+91 9876543225",
      country: "India",
      hasGst: true,
      gstNo: "08ABCDE9012F1Z5",
      bankName: "State Bank of India",
      accountNo: "345678901234",
      ifscCode: "SBIN0001234",
      bankAccounts: [
        {
          bankName: "State Bank of India",
          ifscCode: "SBIN0001234",
          accountNo: "345678901234",
        },
        {
          bankName: "Axis Bank",
          ifscCode: "UTIB0001234",
          accountNo: "456789012345",
        },
      ] as BankAccount[],
      address1: "Sutlej Textiles Mill",
      address2: "Bhilwara Road",
      pincode: "311001",
      state: "Rajasthan",
      city: "Bhilwara",
      addresses: [
        {
          id: "addr_sutlej1",
          city: "Bhilwara",
          name: "Sutlej Head Office",
          type: "Office",
          state: "Rajasthan",
          country: "India",
          pincode: "311001",
          address1: "Sutlej Textiles Mill",
          address2: "Bhilwara Road",
          contactNo: "+91 9876543224",
          isBillingDefault: true,
        },
        {
          id: "addr_sutlej2",
          city: "Delhi",
          name: "Sutlej Delhi Office",
          type: "Office",
          state: "Delhi",
          country: "India",
          pincode: "110001",
          address1: "Sutlej Showroom, Connaught Place",
          address2: "New Delhi",
          contactNo: "+91 9876543225",
          isBillingDefault: false,
        },
      ] as VendorAddress[],
      paymentAttachments: [] as PaymentAttachment[],
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system@erp.com",
    },
    // 4. Bombay Dyeing
    {
      vendorCode: "VEN004",
      brandName: "Bombay Dyeing",
      contactName: "Vikram Mehta",
      email: "vikram@bombaydyeing.com",
      altEmail: "",
      contactNo: "+91 9876543226",
      altContactNo: "",
      country: "India",
      hasGst: true,
      gstNo: "27ABCDE3456F1Z5",
      bankName: "ICICI Bank",
      accountNo: "567890123456",
      ifscCode: "ICIC0000456",
      bankAccounts: [
        {
          bankName: "ICICI Bank",
          ifscCode: "ICIC0000456",
          accountNo: "567890123456",
        },
      ] as BankAccount[],
      address1: "Bombay Dyeing Mills",
      address2: "Worli",
      pincode: "400018",
      state: "Maharashtra",
      city: "Mumbai",
      addresses: [
        {
          id: "addr_bd1",
          city: "Mumbai",
          name: "Bombay Dyeing Head Office",
          type: "Office",
          state: "Maharashtra",
          country: "India",
          pincode: "400018",
          address1: "Bombay Dyeing Mills",
          address2: "Worli",
          contactNo: "+91 9876543226",
          isBillingDefault: true,
        },
      ] as VendorAddress[],
      paymentAttachments: [] as PaymentAttachment[],
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system@erp.com",
    },
    // 5. Welspun India
    {
      vendorCode: "VEN005",
      brandName: "Welspun India",
      contactName: "Rakesh Gupta",
      email: "rakesh@welspun.com",
      altEmail: "rakesh.alt@welspun.com",
      contactNo: "+91 9876543227",
      altContactNo: "+91 9876543228",
      country: "India",
      hasGst: true,
      gstNo: "24ABCDE7890F1Z5",
      bankName: "HDFC Bank",
      accountNo: "678901234567",
      ifscCode: "HDFC0000789",
      bankAccounts: [
        {
          bankName: "HDFC Bank",
          ifscCode: "HDFC0000789",
          accountNo: "678901234567",
        },
        {
          bankName: "Axis Bank",
          ifscCode: "UTIB0000789",
          accountNo: "789012345678",
        },
      ] as BankAccount[],
      address1: "Welspun House",
      address2: "Chandivali, Andheri East",
      pincode: "400072",
      state: "Maharashtra",
      city: "Mumbai",
      addresses: [
        {
          id: "addr_welspun1",
          city: "Mumbai",
          name: "Welspun Corporate Office",
          type: "Office",
          state: "Maharashtra",
          country: "India",
          pincode: "400072",
          address1: "Welspun House",
          address2: "Chandivali, Andheri East",
          contactNo: "+91 9876543227",
          isBillingDefault: true,
        },
        {
          id: "addr_welspun2",
          city: "Ahmedabad",
          name: "Welspun Gujarat Plant",
          type: "Factory",
          state: "Gujarat",
          country: "India",
          pincode: "380015",
          address1: "Welspun Gujarat Plant",
          address2: "Sanand",
          contactNo: "+91 9876543228",
          isBillingDefault: false,
        },
      ] as VendorAddress[],
      paymentAttachments: [] as PaymentAttachment[],
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system@erp.com",
    },
    // 6. Vardhman Textiles
    {
      vendorCode: "VEN006",
      brandName: "Vardhman Textiles",
      contactName: "Manoj Verma",
      email: "manoj@vardhman.com",
      altEmail: "",
      contactNo: "+91 9876543229",
      altContactNo: "",
      country: "India",
      hasGst: true,
      gstNo: "03ABCDE1234F1Z5",
      bankName: "Punjab National Bank",
      accountNo: "789012345678",
      ifscCode: "PUNB0001234",
      bankAccounts: [
        {
          bankName: "Punjab National Bank",
          ifscCode: "PUNB0001234",
          accountNo: "789012345678",
        },
      ] as BankAccount[],
      address1: "Vardhman Mill",
      address2: "Ludhiana Road",
      pincode: "141001",
      state: "Punjab",
      city: "Ludhiana",
      addresses: [
        {
          id: "addr_vardhman1",
          city: "Ludhiana",
          name: "Vardhman Head Office",
          type: "Office",
          state: "Punjab",
          country: "India",
          pincode: "141001",
          address1: "Vardhman Mill",
          address2: "Ludhiana Road",
          contactNo: "+91 9876543229",
          isBillingDefault: true,
        },
      ] as VendorAddress[],
      paymentAttachments: [] as PaymentAttachment[],
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system@erp.com",
    },
    // 7. Trident Group
    {
      vendorCode: "VEN007",
      brandName: "Trident Group",
      contactName: "Sanjay Bansal",
      email: "sanjay@trident.com",
      altEmail: "sanjay.alt@trident.com",
      contactNo: "+91 9876543230",
      altContactNo: "+91 9876543231",
      country: "India",
      hasGst: true,
      gstNo: "03ABCDE5678F1Z5",
      bankName: "ICICI Bank",
      accountNo: "890123456789",
      ifscCode: "ICIC0000789",
      bankAccounts: [
        {
          bankName: "ICICI Bank",
          ifscCode: "ICIC0000789",
          accountNo: "890123456789",
        },
        {
          bankName: "HDFC Bank",
          ifscCode: "HDFC0000789",
          accountNo: "901234567890",
        },
      ] as BankAccount[],
      address1: "Trident House",
      address2: "Industrial Area, Budhni",
      pincode: "466445",
      state: "Madhya Pradesh",
      city: "Budhni",
      addresses: [
        {
          id: "addr_trident1",
          city: "Budhni",
          name: "Trident Corporate Office",
          type: "Office",
          state: "Madhya Pradesh",
          country: "India",
          pincode: "466445",
          address1: "Trident House",
          address2: "Industrial Area, Budhni",
          contactNo: "+91 9876543230",
          isBillingDefault: true,
        },
        {
          id: "addr_trident2",
          city: "Delhi",
          name: "Trident Delhi Office",
          type: "Office",
          state: "Delhi",
          country: "India",
          pincode: "110001",
          address1: "Trident Showroom, Connaught Place",
          address2: "New Delhi",
          contactNo: "+91 9876543231",
          isBillingDefault: false,
        },
      ] as VendorAddress[],
      paymentAttachments: [] as PaymentAttachment[],
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system@erp.com",
    },
    // 8. Nahar Spinning
    {
      vendorCode: "VEN008",
      brandName: "Nahar Spinning",
      contactName: "Pankaj Jain",
      email: "pankaj@nahar.com",
      altEmail: "",
      contactNo: "+91 9876543232",
      altContactNo: "",
      country: "India",
      hasGst: true,
      gstNo: "03ABCDE9012F1Z5",
      bankName: "Axis Bank",
      accountNo: "012345678901",
      ifscCode: "UTIB0000123",
      bankAccounts: [
        {
          bankName: "Axis Bank",
          ifscCode: "UTIB0000123",
          accountNo: "012345678901",
        },
      ] as BankAccount[],
      address1: "Nahar Spinning Mills",
      address2: "Lalru",
      pincode: "140501",
      state: "Punjab",
      city: "Lalru",
      addresses: [
        {
          id: "addr_nahar1",
          city: "Lalru",
          name: "Nahar Head Office",
          type: "Office",
          state: "Punjab",
          country: "India",
          pincode: "140501",
          address1: "Nahar Spinning Mills",
          address2: "Lalru",
          contactNo: "+91 9876543232",
          isBillingDefault: true,
        },
      ] as VendorAddress[],
      paymentAttachments: [] as PaymentAttachment[],
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system@erp.com",
    },
    // 9. Garden Silk Mills
    {
      vendorCode: "VEN009",
      brandName: "Garden Silk Mills",
      contactName: "Karan Shah",
      email: "karan@gardensilk.com",
      altEmail: "karan.alt@gardensilk.com",
      contactNo: "+91 9876543233",
      altContactNo: "+91 9876543234",
      country: "India",
      hasGst: true,
      gstNo: "24ABCDE1234F1Z5",
      bankName: "HDFC Bank",
      accountNo: "123456789012",
      ifscCode: "HDFC0000456",
      bankAccounts: [
        {
          bankName: "HDFC Bank",
          ifscCode: "HDFC0000456",
          accountNo: "123456789012",
        },
        {
          bankName: "ICICI Bank",
          ifscCode: "ICIC0000456",
          accountNo: "234567890123",
        },
      ] as BankAccount[],
      address1: "Garden Silk Mills",
      address2: "Surat - Navsari Road",
      pincode: "394210",
      state: "Gujarat",
      city: "Surat",
      addresses: [
        {
          id: "addr_garden1",
          city: "Surat",
          name: "Garden Silk Head Office",
          type: "Office",
          state: "Gujarat",
          country: "India",
          pincode: "394210",
          address1: "Garden Silk Mills",
          address2: "Surat - Navsari Road",
          contactNo: "+91 9876543233",
          isBillingDefault: true,
        },
        {
          id: "addr_garden2",
          city: "Mumbai",
          name: "Garden Silk Mumbai Office",
          type: "Office",
          state: "Maharashtra",
          country: "India",
          pincode: "400013",
          address1: "Garden Silk Showroom, Lower Parel",
          address2: "Mumbai",
          contactNo: "+91 9876543234",
          isBillingDefault: false,
        },
      ] as VendorAddress[],
      paymentAttachments: [] as PaymentAttachment[],
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system@erp.com",
    },
    // 10. Indo Count Industries (exact match to your sample)
    {
      vendorCode: "VEN010",
      brandName: "Indo Count Industries",
      contactName: "Nitin Joshi",
      email: "nitin@indocount.com",
      altEmail: "",
      contactNo: "+91 9876543235",
      altContactNo: "+91",
      country: "",
      hasGst: true,
      gstNo: "07ABCDE1234F1Z5",
      bankName: null,
      accountNo: null,
      ifscCode: null,
      bankAccounts: [
        {
          bankName: "HDFC Bank",
          ifscCode: "HDFC0TEST00",
          accountNo: "98765432101234",
        },
      ] as BankAccount[],
      address1: "",
      address2: "",
      pincode: "",
      state: "",
      city: "",
      addresses: [
        {
          id: "oio17jag",
          city: "Thane",
          name: "Rohan Mehta",
          type: "Office",
          state: "Maharashtra",
          country: "India",
          pincode: "421302",
          address1: "Warehouse No. 18, Metro Logistics Park",
          address2: "Bhiwandi Industrial Area",
          contactNo: "+91 9000012345",
          isBillingDefault: true,
        },
      ] as VendorAddress[],
      paymentAttachments: [] as PaymentAttachment[],
      isActive: true,
      isDeleted: false,
      createdBy: "system",
      updatedBy: "system@erp.com",
    },
    // 11. Haldiram's - Refreshment / Food Supplier
    // {
    //   vendorCode: "VEN011",
    //   brandName: "Haldiram's",
    //   contactName: "Amit Agarwal",
    //   email: "amit.agarwal@haldirams.example",
    //   altEmail: "",
    //   contactNo: "+91 9876543236",
    //   altContactNo: "",
    //   country: "India",
    //   hasGst: true,
    //   gstNo: "07AAAAA1111A1Z1",
    //   bankName: "HDFC Bank",
    //   accountNo: "987654321001",
    //   ifscCode: "HDFC0001122",

    //   bankAccounts: [
    //     {
    //       bankName: "HDFC Bank",
    //       ifscCode: "HDFC0001122",
    //       accountNo: "987654321001",
    //     },
    //   ] as BankAccount[],

    //   address1: "Food Supply Division",
    //   address2: "Industrial Area",
    //   pincode: "110020",
    //   state: "Delhi",
    //   city: "New Delhi",

    //   addresses: [
    //     {
    //       id: "addr_haldiram1",
    //       city: "New Delhi",
    //       name: "Haldiram's Food Supply",
    //       type: "Office",
    //       state: "Delhi",
    //       country: "India",
    //       pincode: "110020",
    //       address1: "Food Supply Division",
    //       address2: "Industrial Area",
    //       contactNo: "+91 9876543236",
    //       isBillingDefault: true,
    //     },
    //     {
    //       id: "addr_haldiram2",
    //       city: "Gurugram",
    //       name: "Haldiram's Delivery Point",
    //       type: "Warehouse",
    //       state: "Haryana",
    //       country: "India",
    //       pincode: "122016",
    //       address1: "Commercial Food Distribution Centre",
    //       address2: "Industrial Area",
    //       contactNo: "+91 9876543237",
    //       isBillingDefault: false,
    //     },
    //   ] as VendorAddress[],

    //   paymentAttachments: [] as PaymentAttachment[],

    //   isActive: true,
    //   isDeleted: false,
    //   createdBy: "system",
    //   updatedBy: "system@erp.com",
    // },

    // 12. Bikaji Foods - Refreshment / Snacks Supplier
    // {
    //   vendorCode: "VEN012",
    //   brandName: "Bikaji Foods",
    //   contactName: "Rajesh Bansal",
    //   email: "rajesh.bansal@bikaji.example",
    //   altEmail: "",
    //   contactNo: "+91 9876543238",
    //   altContactNo: "",
    //   country: "India",
    //   hasGst: true,
    //   gstNo: "08BBBBB2222B1Z2",
    //   bankName: "ICICI Bank",
    //   accountNo: "987654321002",
    //   ifscCode: "ICIC0002233",

    //   bankAccounts: [
    //     {
    //       bankName: "ICICI Bank",
    //       ifscCode: "ICIC0002233",
    //       accountNo: "987654321002",
    //     },
    //     {
    //       bankName: "Axis Bank",
    //       ifscCode: "UTIB0002233",
    //       accountNo: "987654321003",
    //     },
    //   ] as BankAccount[],

    //   address1: "Food Distribution Centre",
    //   address2: "Industrial Area",
    //   pincode: "302013",
    //   state: "Rajasthan",
    //   city: "Jaipur",

    //   addresses: [
    //     {
    //       id: "addr_bikaji1",
    //       city: "Jaipur",
    //       name: "Bikaji Food Distribution Centre",
    //       type: "Office",
    //       state: "Rajasthan",
    //       country: "India",
    //       pincode: "302013",
    //       address1: "Food Distribution Centre",
    //       address2: "Industrial Area",
    //       contactNo: "+91 9876543238",
    //       isBillingDefault: true,
    //     },
    //   ] as VendorAddress[],

    //   paymentAttachments: [] as PaymentAttachment[],

    //   isActive: true,
    //   isDeleted: false,
    //   createdBy: "system",
    //   updatedBy: "system@erp.com",
    // },
  ];

  // Insert vendors inside a transaction
  await db.transaction(async (tx) => {
    let inserted = 0;

    for (const vendor of vendorData) {
      const insertValues = {
        vendorCode: vendor.vendorCode,
        brandName: vendor.brandName,
        contactName: vendor.contactName ?? null,
        email: vendor.email ?? null,
        altEmail: vendor.altEmail ?? null,
        contactNo: vendor.contactNo ?? null,
        altContactNo: vendor.altContactNo ?? null,
        country: vendor.country ?? null,
        hasGst: vendor.hasGst ?? false,
        gstNo: vendor.gstNo ?? null,
        bankName: vendor.bankName ?? null,
        accountNo: vendor.accountNo ?? null,
        ifscCode: vendor.ifscCode ?? null,
        bankAccounts: vendor.bankAccounts ?? ([] as BankAccount[]),
        address1: vendor.address1 ?? null,
        address2: vendor.address2 ?? null,
        pincode: vendor.pincode ?? null,
        state: vendor.state ?? null,
        city: vendor.city ?? null,
        addresses: vendor.addresses ?? ([] as VendorAddress[]),
        paymentAttachments: vendor.paymentAttachments ?? ([] as PaymentAttachment[]),
        isActive: vendor.isActive ?? true,
        isDeleted: vendor.isDeleted ?? false,
        createdBy: vendor.createdBy,
        updatedBy: vendor.updatedBy ?? vendor.createdBy,
      };

      const [result] = await tx
        .insert(vendorsTable)
        .values(insertValues)
        .onConflictDoNothing()
        .returning({ id: vendorsTable.id });

      if (result) inserted++;
    }

    console.log(`[master-seed] Vendors: ${inserted} inserted`);
  });
}